import React, { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react';

const STORAGE_KEY = 'connection-language';
const LanguageContext = createContext();

const messages = {
  pt: {
    'app.loadingSession': 'Verificando autenticação...',
    'app.sessionError': 'Não foi possível carregar a sessão. Tente novamente.',
    'layout.skipToContent': 'Saltar para o conteúdo principal',
    'layout.loadingProfile': 'A carregar perfil...',
    'preferences.lightMode': 'Ativar modo claro',
    'preferences.darkMode': 'Ativar modo escuro',
    'preferences.changeToEnglish': 'Mudar idioma para inglês',
    'preferences.changeToPortuguese': 'Mudar idioma para português',
    'preferences.theme': 'Tema',
    'preferences.light': 'Claro',
    'preferences.dark': 'Escuro',
    'dashboard.loading': 'A carregar painel...',
    'dashboard.welcome': 'Bem-vindo(a)',
    'dashboard.user': 'Utilizador',
    'dashboard.verified': 'Verificado',
    'dashboard.sectorMissing': 'Setor não definido',
    'dashboard.emailMissing': 'Email não definido',
    'dashboard.locationMissing': 'Localização não definida',
    'dashboard.memberSince': 'Membro desde',
    'dashboard.newPost': 'Nova publicação',
    'dashboard.allProvinces': 'Todas as províncias',
    'dashboard.logout': 'Sair da conta',
    'dashboard.modules': 'Módulos',
    'dashboard.activeModulesCount': '{count} módulo(s) ativo(s)',
    'modules.loading': 'A carregar módulos...',
    'modules.market.name': 'Produtos e serviços',
    'modules.market.description': 'Cadastre os seus produtos e serviços',
    'modules.alert.name': 'Alertas',
    'modules.alert.description': 'Receba solicitações e pedidos de cotação',
    'modules.open': 'Abrir {name}',
    'modules.subscribe': 'Subscrever {name}',
    'modules.active': 'Ativo',
    'modules.locked': 'Bloqueado',
    'modules.available': 'Disponível',
    'modules.unavailable': 'Indisponível — subscreva para aceder',
    'nav.home': 'Página inicial',
    'nav.primary': 'Navegação principal',
    'nav.suppliers': 'Fornecedores',
    'nav.stores': 'Lojas',
    'nav.feed': 'Publicações',
    'feed.title': 'Publicações',
    'feed.description': 'Conheça projetos, trabalhos e histórias das empresas da Connection Mozambique.',
    'feed.companyFilter': 'Filtrar publicações por empresa',
    'feed.allCompanies': 'Todas as empresas',
    'feed.loading': 'A carregar publicações...',
    'feed.loadError': 'Não foi possível carregar as publicações. Tente novamente.',
    'feed.retry': 'Tentar novamente',
    'feed.empty': 'Nenhuma publicação encontrada',
    'feed.emptyHelp': 'As novas publicações das empresas aparecerão aqui.',
    'feed.emptyCompany': 'Esta empresa ainda não possui publicações disponíveis.',
    'feed.noDescription': 'Publicação sem descrição.',
    'feed.dateUnknown': 'Data não disponível',
    'feed.openPost': 'Abrir publicação de',
    'gallery.label': 'Galeria de publicações',
    'gallery.empty': 'Nenhuma publicação encontrada',
    'gallery.emptyHelp': 'As publicações desta empresa aparecerão aqui.',
    'gallery.companyUnknown': 'empresa',
    'gallery.openPost': 'Abrir publicação de {company}',
    'gallery.imageAlt': 'Trabalho publicado por {company}',
    'profile.loading': 'A carregar perfil...',
    'profile.tabs.home': 'Início',
    'profile.tabs.about': 'Sobre',
    'profile.tabs.posts': 'Publicações',
    'profile.tabs.repository': 'Repositório',
    'profile.companyInfo': 'Informações da empresa',
    'profile.generalInfo': 'Informações gerais',
    'profile.details': 'Detalhes',
    'profile.aboutCompany': 'Sobre a empresa',
    'profile.mission': 'Missão, visão e valores',
    'profile.address': 'Endereço',
    'profile.contact': 'Contacto',
    'profile.email': 'Email',
    'profile.sector': 'Setor',
    'profile.entityType': 'Tipo de entidade',
    'profile.location': 'Localização',
    'profile.provinceDistrict': 'Província/Distrito',
    'profile.productionCapacity': 'Capacidade de produção',
    'profile.notProvided': 'Não informado',
    'profile.noContent': 'Nenhum conteúdo disponível.',
    'profile.noInformation': 'Nenhuma informação registada.',
    'profile.visits': 'Visitas',
    'profile.connections': 'Conexões',
    'profile.quotes': 'Cotações',
    'profile.edit': 'Editar perfil',
    'profile.readMore': 'Ler mais',
    'profile.readLess': 'Ver menos',
    'profile.copyLink': 'Copiar ligação',
    'profile.copySuccess': 'Ligação copiada.',
    'profile.copyError': 'Não foi possível copiar a ligação.',
    'profile.imageTooLarge': 'A imagem é demasiado grande (máximo de 25 MB).',
    'profile.imageTypeError': 'Formato não suportado. Use JPEG, PNG ou WEBP.',
    'profile.imageProcessError': 'Não foi possível processar a imagem.',
    'profile.cropError': 'Não foi possível recortar a imagem.',
    'profile.photoSuccess': 'Fotografia atualizada.',
    'profile.photoError': 'Não foi possível atualizar a fotografia.',
    'profile.blocked': 'Empresa bloqueada',
    'profile.block': 'Bloquear empresa',
    'profile.unblock': 'Desbloquear empresa',
    'profile.report': 'Denunciar empresa',
    'profile.loginForOptions': 'Inicie sessão para aceder a estas opções.',
    'profile.noCover': 'Sem fotografia de capa',
    'profile.companyNotFound': 'Empresa não encontrada.',
    'profile.loadError': 'Não foi possível carregar o perfil.',
    'profile.authConnect': 'Inicie sessão para se conectar a empresas.',
    'profile.connectSuccess': 'Pedido de conexão enviado.',
    'profile.connectError': 'Não foi possível enviar o pedido de conexão.',
    'profile.cancelConnectionSuccess': 'Pedido de conexão cancelado.',
    'profile.cancelConnectionError': 'Não foi possível cancelar o pedido de conexão.',
    'profile.disconnectSuccess': 'Conexão terminada.',
    'profile.disconnectError': 'Não foi possível terminar a conexão.',
    'profile.authReport': 'Inicie sessão para denunciar uma empresa.',
    'profile.reasonRequired': 'Selecione um motivo.',
    'profile.reportSuccess': 'Denúncia enviada. Obrigado pelo feedback.',
    'profile.reportError': 'Não foi possível enviar a denúncia.',
    'profile.authBlock': 'Inicie sessão para bloquear uma empresa.',
    'profile.blockSuccess': 'Empresa bloqueada.',
    'profile.blockError': 'Não foi possível bloquear a empresa.',
    'profile.unblockSuccess': 'Empresa desbloqueada.',
    'profile.unblockError': 'Não foi possível desbloquear a empresa.',
    'profile.processingImage': 'A processar imagem...',
    'profile.cropTitle': 'Recortar imagem',
    'profile.cropAlt': 'Imagem para recortar',
    'profile.cancel': 'Cancelar',
    'profile.applyCrop': 'Aplicar recorte',
    'profile.close': 'Fechar',
    'profile.share': 'Partilhar perfil',
    'profile.shareFacebook': 'Partilhar no Facebook',
    'profile.shareTwitter': 'Partilhar no X',
    'profile.shareWhatsApp': 'Partilhar no WhatsApp',
    'profile.shareEmail': 'Partilhar por email',
    'profile.connect': 'Conectar',
    'profile.cancelRequest': 'Cancelar pedido',
    'profile.disconnect': 'Desconectar',
    'profile.loginToConnect': 'Inicie sessão para conectar',
    'profile.openStore': 'Ir para a loja',
    'profile.call': 'Ligar',
    'profile.sendEmail': 'Enviar email',
    'profile.reportTitle': 'Denunciar empresa',
    'profile.sendReport': 'Enviar denúncia',
    'profile.blockTitle': 'Bloquear empresa',
    'profile.blockWarning': 'Ao bloquear esta empresa:',
    'profile.blockEffectConnections': 'Não poderá enviar pedidos de conexão',
    'profile.blockEffectQuotes': 'Não receberá pedidos de cotação',
    'profile.customReason': 'Descreva o motivo em detalhe',
    'profile.confirmBlock': 'Confirmar bloqueio',
    'profile.disconnectTitle': 'Confirmar desconexão',
    'profile.disconnectQuestion': 'Tem a certeza de que deseja desconectar-se de {company}?',
    'profile.disconnectEffect': 'Esta empresa deixará de fazer parte da sua lista de clientes.',
    'profile.reportReasonPrompt': 'Selecione o motivo da denúncia:',
    'profile.blockReasonPrompt': 'Selecione o motivo do bloqueio:',
    'profile.reason.inappropriate': 'Conteúdo inadequado',
    'profile.reason.spam': 'Spam ou mensagens indesejadas',
    'profile.reason.personal': 'Problemas pessoais',
    'profile.reason.unnecessary': 'Empresa irrelevante',
    'profile.reason.offensive': 'Conteúdo ofensivo',
    'profile.reason.falseInformation': 'Informações falsas',
    'profile.reason.misconduct': 'Comportamento inadequado',
    'profile.reason.terms': 'Violação dos termos',
    'profile.reason.other': 'Outro motivo',
    'profileEdit.title': 'Editar perfil',
    'profileEdit.description': 'Gira as informações da sua empresa',
    'profileEdit.loading': 'A carregar editor de perfil...',
    'profileEdit.tabs.profile': 'Perfil',
    'profileEdit.tabs.password': 'Palavra-passe',
    'profileEdit.tabs.bank': 'Dados bancários',
    'profileEdit.tabs.social': 'Redes sociais',
    'profileEdit.tabs.showcase': 'Montra',
    'profileEdit.companyName': 'Nome da empresa',
    'profileEdit.name': 'Nome',
    'profileEdit.acronym': 'Sigla',
    'profileEdit.bio': 'Biografia (máximo de {count} caracteres)',
    'profileEdit.bioPlaceholder': 'Escreva uma breve descrição da empresa...',
    'profileEdit.province': 'Província',
    'profileEdit.productionCapacity': 'Capacidade de produção da atividade principal',
    'profileEdit.save': 'Guardar alterações',
    'profileEdit.saveSocial': 'Guardar redes sociais',
    'profileEdit.saveSuccess': 'Dados atualizados.',
    'profileEdit.saveError': 'Não foi possível atualizar os dados.',
    'profileEdit.userMissing': 'Utilizador não encontrado.',
    'profileEdit.youtubeHelp': 'Cole a ligação completa do vídeo do YouTube que pretende destacar.',
    'profileEdit.videoPreview': 'Pré-visualização do vídeo',
    'personalProfile.defaultName': 'Utilizador',
    'personalProfile.changePhoto': 'Alterar fotografia do perfil',
    'personalProfile.invalidPhoto': 'Selecione uma imagem com tamanho máximo de 5 MB.',
    'personalProfile.photoSuccess': 'Fotografia atualizada.',
    'personalProfile.photoError': 'Não foi possível atualizar a fotografia.',
    'personalProfile.province': 'Província',
    'personalProfile.saveProvince': 'Guardar província',
    'personalProfile.locationSuccess': 'Localização atualizada.',
    'personalProfile.locationError': 'Não foi possível atualizar a localização.',
    'personalProfile.logout': 'Terminar sessão',
    'personalProfile.logoutError': 'Não foi possível terminar a sessão.',
    'postDetail.loadError': 'Não foi possível carregar a publicação.',
    'postDetail.notFound': 'Publicação não encontrada',
    'postDetail.back': 'Voltar',
    'postDetail.authRequired': 'Inicie sessão para realizar esta ação.',
    'postDetail.permissionDenied': 'Não tem permissão para realizar esta ação.',
    'postDetail.noDescription': 'Publicação sem descrição.',
    'postDetail.companyUnknown': 'Empresa desconhecida',
    'postDetail.imageAlt': 'Imagem publicada por {company}',
    'postDetail.imageUnavailable': 'Imagem indisponível',
    'postDetail.like': 'Gostar',
    'postDetail.unlike': 'Remover gosto',
    'postDetail.edit': 'Editar',
    'postDetail.delete': 'Eliminar',
    'postDetail.deleteTitle': 'Eliminar publicação?',
    'postDetail.deleteHelp': 'Esta ação é permanente. A publicação, os gostos e os comentários deixarão de estar disponíveis.',
    'postDetail.confirmDelete': 'Eliminar publicação',
    'postDetail.deleting': 'A eliminar...',
    'postDetail.deleteError': 'Não foi possível eliminar a publicação. Tente novamente.',
    'postDetail.share': 'Partilhar',
    'postDetail.report': 'Denunciar',
    'postDetail.copyLink': 'Copiar ligação',
    'postDetail.copySuccess': 'Ligação copiada.',
    'postDetail.copyError': 'Não foi possível copiar a ligação.',
    'postDetail.likeSuccess': 'Publicação adicionada aos gostos.',
    'postDetail.unlikeSuccess': 'Gosto removido.',
    'postDetail.likeError': 'Não foi possível atualizar o gosto.',
    'postDetail.comments': 'Comentários ({count})',
    'postDetail.commentPlaceholder': 'Escreva um comentário...',
    'postDetail.replyPlaceholder': 'Escreva a sua resposta...',
    'postDetail.replying': 'A responder a um comentário...',
    'postDetail.firstComment': 'Seja o primeiro a comentar.',
    'postDetail.reply': 'Responder',
    'postDetail.cancel': 'Cancelar',
    'postDetail.save': 'Guardar',
    'postDetail.reportTitle': 'Denunciar publicação',
    'postDetail.reportHelp': 'Descreva o motivo da denúncia.',
    'postDetail.reportPlaceholder': 'Motivo da denúncia',
    'postDetail.sendReport': 'Enviar denúncia',
    'postDetail.reportReasonRequired': 'Introduza o motivo da denúncia.',
    'postDetail.reportDuplicate': 'Já denunciou esta publicação.',
    'postDetail.reportSuccess': 'Denúncia enviada.',
    'postDetail.reportError': 'Não foi possível enviar a denúncia.',
    'postDetail.commentSuccess': 'Comentário adicionado.',
    'postDetail.commentError': 'Não foi possível adicionar o comentário.',
    'postDetail.replySuccess': 'Resposta enviada.',
    'postDetail.replyError': 'Não foi possível enviar a resposta.',
    'postDetail.commentDeleteSuccess': 'Comentário eliminado.',
    'postDetail.commentDeleteError': 'Não foi possível eliminar o comentário.',
    'postDetail.commentUpdateSuccess': 'Comentário atualizado.',
    'postDetail.commentUpdateError': 'Não foi possível atualizar o comentário.',
    'postDetail.updateSuccess': 'Publicação atualizada.',
    'postEdit.title': 'Editar publicação',
    'postEdit.close': 'Fechar edição',
    'postEdit.description': 'Descrição',
    'postEdit.placeholder': 'Escreva a sua publicação...',
    'postEdit.descriptionRequired': 'A descrição não pode estar vazia.',
    'postEdit.saveError': 'Não foi possível atualizar a publicação. Tente novamente.',
    'postEdit.saving': 'A guardar...',
    'postEdit.save': 'Guardar alterações',
    'nav.signIn': 'Entrar',
    'nav.openMenu': 'Abrir menu',
    'nav.closeMenu': 'Fechar menu',
    'nav.companies': 'Empresas',
    'nav.quotes': 'Cotações',
    'nav.sentQuotes': 'Meus pedidos',
    'market.sentQuotes.title': 'Pedidos enviados às lojas',
    'market.sentQuotes.description': 'Acompanhe os pedidos de cotação que enviou diretamente pelo Mercado.',
    'market.sentQuotes.loadError': 'Não foi possível carregar os seus pedidos.',
    'market.sentQuotes.empty': 'Ainda não enviou pedidos a lojas',
    'market.sentQuotes.emptyHelp': 'Explore o Mercado e peça uma cotação diretamente a uma loja.',
    'market.sentQuotes.explore': 'Explorar lojas',
    'market.sentQuotes.callStore': 'Ligar para a loja',
    'market.sentQuotes.emailStore': 'Enviar email',
    'market.sentQuotes.viewStore': 'Ver loja',
    'market.sentQuotes.responseTitle': 'Resposta da loja',
    'market.sentQuotes.totalPrice': 'Preço total',
    'market.sentQuotes.validUntil': 'Válida até',
    'market.sentQuotes.status.pending': 'A aguardar resposta',
    'market.sentQuotes.status.answered': 'Respondido',
    'market.sentQuotes.status.expired': 'Expirado',
    'market.sentQuotes.status.cancelled': 'Cancelado',
    'market.sentQuotes.status.accepted': 'Aceite',
    'market.sentQuotes.status.rejected': 'Recusado',
    'market.sentQuotes.status.revision_requested': 'Revisão solicitada',
    'market.sentQuotes.accept': 'Aceitar proposta',
    'market.sentQuotes.reject': 'Recusar',
    'market.sentQuotes.requestRevision': 'Pedir revisão',
    'market.sentQuotes.decision.accepted': 'Aceitar proposta',
    'market.sentQuotes.decision.rejected': 'Recusar proposta',
    'market.sentQuotes.decision.revision_requested': 'Pedir revisão à loja',
    'market.sentQuotes.decisionNote': 'Nota para a loja',
    'market.sentQuotes.revisionRequired': 'Explique o que deve ser revisto.',
    'market.sentQuotes.decisionError': 'Não foi possível atualizar o pedido.',
    'nav.notifications': 'Notificações',
    'nav.dashboard': 'Painel',
    'nav.profile': 'Meu perfil',
    'nav.signOut': 'Sair',
    'nav.signInOrRegister': 'Entrar / Registar',
    'nav.verificationRequired': 'Verificação necessária',
    'verification.title': 'Conta em verificação',
    'verification.description': 'Os seus dados estão a ser verificados. Receberá uma notificação quando o processo terminar.',
    'verification.limited': 'A sua conta não está verificada. Algumas funcionalidades estão limitadas.',
    'footer.about': 'A maior plataforma empresarial de Moçambique. Ligamos compradores a fornecedores verificados, facilitando negócios e impulsionando a economia nacional.',
    'footer.verifiedCompany': 'Empresa verificada',
    'footer.quickLinks': 'Links rápidos',
    'footer.legalInformation': 'Informações legais',
    'footer.contacts': 'Contactos',
    'footer.followUs': 'Siga-nos',
    'footer.home': 'Início',
    'footer.explore': 'Explorar empresas',
    'footer.services': 'Serviços',
    'footer.aboutUs': 'Sobre nós',
    'footer.contact': 'Contacto',
    'footer.termsConditions': 'Termos e condições',
    'footer.privacyPolicy': 'Política de privacidade',
    'footer.cookiesPolicy': 'Política de cookies',
    'footer.hours': 'Seg - Sáb: 8:00 - 17:00',
    'footer.copyright': '© {year} Connection Mozambique, LDA — Plataforma Empresarial de Moçambique. Todos os direitos reservados.',
    'footer.terms': 'Termos',
    'footer.privacy': 'Privacidade',
    'payment.loading': 'A carregar módulo...',
    'payment.notFoundTitle': 'Módulo não encontrado',
    'payment.notFoundDescription': 'O módulo que está a tentar abrir não existe ou foi removido.',
    'payment.backHome': 'Voltar à página inicial',
    'payment.validity': 'Validade',
    'payment.oneYear': '1 ano',
    'payment.oneMonth': '1 mês',
    'payment.price': 'Preço',
    'payment.moduleValue': 'Valor do módulo',
    'payment.reference': 'Referência',
    'payment.phone': 'Telefone M-Pesa',
    'payment.phoneInvalid': 'Número inválido. Use nove dígitos e um prefixo móvel moçambicano válido.',
    'payment.phoneHelp': 'Introduza os nove dígitos do número, por exemplo 841234567.',
    'payment.submit': 'Pagar via M-Pesa',
    'payment.processing': 'A processar pagamento',
    'payment.success': 'Pagamento processado com sucesso. A sua subscrição foi ativada.',
    'payment.continue': 'Continuar para o módulo',
    'payment.confirmingActivation': 'Pagamento aprovado. A confirmar a ativação do módulo...',
    'payment.waitingActivation': 'A aguardar ativação',
    'payment.error.configuration': 'O serviço de pagamento não está configurado neste ambiente.',
    'payment.error.validation': 'Verifique o módulo e o número de telefone antes de continuar.',
    'payment.error.authentication': 'A sessão terminou. Entre novamente para continuar.',
    'payment.error.connection': 'Não foi possível contactar o serviço de autenticação. Tente novamente dentro de instantes.',
    'payment.error.duplicate': 'Este pagamento já foi processado. Aguarde a confirmação da ativação.',
    'payment.error.generic': 'Não foi possível processar o pagamento.',
    'auth.email': 'Email',
    'auth.password': 'Palavra-passe',
    'auth.currentPassword': 'Palavra-passe atual',
    'auth.newPassword': 'Nova palavra-passe',
    'auth.confirmPassword': 'Confirmar nova palavra-passe',
    'auth.welcomeBack': 'Bem-vindo de volta',
    'auth.signInDescription': 'Entre com a sua conta para aceder à plataforma',
    'auth.accountLocked': 'Conta bloqueada',
    'auth.signingIn': 'A entrar...',
    'auth.signInWithEmail': 'Entrar com email',
    'auth.or': 'ou',
    'auth.continueGoogle': 'Continuar com Google',
    'auth.forgotPassword': 'Esqueceu a palavra-passe?',
    'auth.noAccount': 'Não tem conta?',
    'auth.register': 'Registe-se',
    'auth.showPassword': 'Mostrar palavra-passe',
    'auth.hidePassword': 'Ocultar palavra-passe',
    'auth.security.secure': 'Ligação segura',
    'auth.security.standard': 'Verificação padrão',
    'auth.security.additional': 'Verificação adicional necessária',
    'password.changeTitle': 'Alterar palavra-passe',
    'password.updating': 'A atualizar...',
    'password.update': 'Atualizar palavra-passe',
    'password.error.mismatch': 'As palavras-passe não coincidem.',
    'password.error.unauthenticated': 'Utilizador não autenticado.',
    'password.error.generic': 'Não foi possível atualizar a palavra-passe. Verifique os dados introduzidos.',
    'password.error.weak': 'A nova palavra-passe deve ter pelo menos 8 caracteres.',
    'password.error.same': 'A nova palavra-passe deve ser diferente da atual.',
    'password.error.current': 'A palavra-passe atual está incorreta.',
    'password.error.provider': 'Esta conta não utiliza palavra-passe. Entre através do fornecedor associado.',
    'password.error.changeTooMany': 'Demasiadas tentativas. Aguarde e tente novamente.',
    'password.requirements': 'Utilize pelo menos 8 caracteres.',
    'password.success': 'Palavra-passe atualizada com sucesso.',
    'common.cancel': 'Cancelar',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'bank.title': 'Dados bancários',
    'bank.description': 'Gira as contas usadas para receber pagamentos. Estes dados devem pertencer ao titular indicado.',
    'bank.addTab': 'Adicionar conta',
    'bank.editTab': 'Editar conta',
    'bank.listTab': 'Contas guardadas',
    'bank.bank': 'Banco',
    'bank.accountNumber': 'Número da conta',
    'bank.accountHolder': 'Titular da conta',
    'bank.nib': 'NIB',
    'bank.iban': 'IBAN',
    'bank.add': 'Guardar conta',
    'bank.update': 'Atualizar conta',
    'bank.saving': 'A guardar...',
    'bank.loading': 'A carregar dados bancários',
    'bank.empty': 'Ainda não existem dados bancários guardados.',
    'bank.required': 'Preencha o número e o titular da conta.',
    'bank.userMissing': 'Não foi possível identificar o utilizador.',
    'bank.loadError': 'Não foi possível carregar os dados bancários.',
    'bank.createSuccess': 'Dados bancários guardados.',
    'bank.updateSuccess': 'Dados bancários atualizados.',
    'bank.saveError': 'Não foi possível guardar os dados bancários.',
    'bank.deleteTitle': 'Eliminar dados bancários?',
    'bank.deleteDescription': 'Esta ação remove permanentemente esta conta bancária do perfil.',
    'bank.deleteSuccess': 'Dados bancários eliminados.',
    'bank.deleteError': 'Não foi possível eliminar os dados bancários.',
    'showcase.title': 'Montra de documentos',
    'showcase.description': 'Consulte e descarregue documentos públicos disponibilizados pela empresa.',
    'showcase.loading': 'A carregar documentos',
    'showcase.empty': 'Ainda não existem documentos publicados.',
    'showcase.document': 'Documento',
    'showcase.noDescription': 'Sem descrição.',
    'showcase.download': 'Descarregar',
    'showcase.loadError': 'Não foi possível carregar os documentos.',
    'showcase.deleteTitle': 'Eliminar documento?',
    'showcase.deleteDescription': 'O documento e o respetivo ficheiro serão removidos permanentemente.',
    'showcase.deleting': 'A eliminar...',
    'showcase.deleteSuccess': 'Documento eliminado.',
    'showcase.deleteError': 'Não foi possível eliminar o documento.',
    'fileUpload.title': 'Publicar documentos',
    'fileUpload.policyTitle': 'Política de publicação de documentos',
    'fileUpload.allowedTitle': 'Documentos permitidos',
    'fileUpload.disallowedTitle': 'Documentos não permitidos',
    'fileUpload.select': 'Selecionar ficheiros',
    'fileUpload.remove': 'Remover ficheiro',
    'fileUpload.description': 'Adicionar descrição...',
    'fileUpload.clear': 'Limpar seleção',
    'fileUpload.start': 'Iniciar publicação',
    'fileUpload.uploading': 'A enviar ({current}/{count})',
    'fileUpload.selectionSummary': '{selected} de {count} ficheiros selecionados · máximo {size} MB por ficheiro',
    'fileUpload.maxFiles': 'Pode enviar no máximo {count} ficheiros de cada vez.',
    'fileUpload.invalidType': 'Formato não suportado: {name}',
    'fileUpload.tooLarge': 'O ficheiro {name} excede o limite de {size} MB.',
    'fileUpload.userMissing': 'Não foi possível identificar o utilizador.',
    'fileUpload.noneSelected': 'Selecione pelo menos um ficheiro.',
    'fileUpload.fileError': 'Não foi possível enviar {name}.',
    'fileUpload.allSuccess': '{count} ficheiro(s) publicado(s) com sucesso.',
    'fileUpload.partialSuccess': '{success} ficheiro(s) publicado(s); {failed} falharam.',
    'fileUpload.noneSuccess': 'Nenhum ficheiro foi publicado.',
    'fileUpload.cancel': 'Cancelar envios',
    'fileUpload.cancelled': 'Os envios foram cancelados.',
    'fileUpload.allowedIntro': 'Publique apenas documentos empresariais destinados ao público, como:',
    'fileUpload.allowedHours': 'Horários de funcionamento',
    'fileUpload.allowedManuals': 'Manuais, garantias e políticas de troca',
    'fileUpload.allowedRegulatory': 'Documentos fiscais ou regulamentares públicos',
    'fileUpload.allowedOther': 'Outros documentos empresariais adequados à divulgação pública',
    'fileUpload.disallowedIntro': 'Não são permitidos:',
    'fileUpload.disallowedPromo': 'Anúncios, banners ou brindes promocionais',
    'fileUpload.disallowedMarketing': 'Campanhas, concursos ou outros materiais de marketing',
    'fileUpload.disallowedUnrelated': 'Conteúdo sem relação com a documentação empresarial',
    'explore.loadError': 'Não foi possível carregar o diretório de empresas. Tente novamente.',
    'common.close': 'Fechar',
    'explore.loading': 'A carregar empresas', 'explore.eyebrow': 'Diretório nacional de empresas',
    'explore.title': 'Encontre empresas, bens e serviços', 'explore.description': 'Pesquise fornecedores por nome, atividade ou localização em Moçambique.',
    'explore.searchPlaceholder': 'Nome, setor ou descrição…', 'explore.searchLabel': 'Pesquisar empresas', 'explore.filters': 'Filtros', 'explore.clear': 'Limpar pesquisa e filtros',
    'explore.results': '{count} empresa(s) encontrada(s)', 'explore.empty': 'Nenhuma empresa corresponde à pesquisa. Ajuste os filtros e tente novamente.',
    'explore.openCompany': 'Abrir perfil de {name}', 'explore.noSector': 'Setor não especificado', 'explore.filterTitle': 'Filtrar empresas',
    'explore.province': 'Província', 'explore.district': 'Distrito', 'explore.sector': 'Setor', 'explore.subsector': 'Subsetor', 'explore.entityType': 'Tipo de entidade',
    'explore.all': 'Todos', 'explore.clearFilters': 'Limpar filtros', 'explore.apply': 'Ver resultados',
    'dashboard.provinceTitle': 'Escolha a sua localização', 'dashboard.provinceDescription': 'Selecione uma província para receber conteúdo regional ou escolha o âmbito nacional.',
    'dashboard.national': 'Nacional — todo Moçambique', 'dashboard.confirmProvince': 'Guardar preferência', 'dashboard.savingProvince': 'A guardar...',
    'dashboard.provinceSaved': 'Preferência de localização guardada.', 'dashboard.provinceError': 'Não foi possível guardar a localização.',
    'dashboard.provinceLoadError': 'Não foi possível carregar as províncias.',
    'dashboard.eyebrow': 'Negócios em todo Moçambique', 'dashboard.title': 'Encontre empresas, produtos e serviços',
    'dashboard.description': 'Descubra fornecedores, compare soluções e crie novas oportunidades comerciais numa única plataforma.',
    'dashboard.searchPlaceholder': 'Pesquisar produtos ou serviços…', 'dashboard.searchLabel': 'Pesquisar produtos ou serviços', 'dashboard.search': 'Pesquisar',
    'dashboard.popular': 'Setores populares:', 'dashboard.exploreCompanies': 'Explorar empresas', 'dashboard.exploreStores': 'Explorar lojas', 'dashboard.requestQuote': 'Pedir cotação',
    'emailVerification.title': 'Verifique o seu email',
    'emailVerification.description': 'Enviámos uma mensagem de verificação para {email}. Abra a ligação recebida para continuar.',
    'emailVerification.support': 'Se precisar de ajuda, contacte',
    'emailVerification.resend': 'Reenviar email de verificação',
    'emailVerification.resending': 'A reenviar...',
    'emailVerification.signOut': 'Sair e voltar ao login',
    'emailVerification.sent': 'Email de verificação reenviado. Consulte a caixa de entrada.',
    'emailVerification.error': 'Não foi possível reenviar o email. Tente novamente mais tarde.',
    'emailVerification.noUser': 'A sessão terminou. Entre novamente para continuar.',
    'password.recoverTitle': 'Recuperar palavra-passe',
    'password.recoverDescription': 'Introduza o seu email para receber as instruções de recuperação.',
    'password.sendLink': 'Enviar ligação de recuperação',
    'password.sending': 'A enviar...',
    'password.backToLogin': 'Voltar ao login',
    'password.didNotReceive': 'Não recebeu o email?',
    'password.resend': 'Reenviar',
    'password.checkSpam': 'Verifique também a pasta de spam ou lixo eletrónico.',
    'password.error.requiredEmail': 'Introduza o seu email.',
    'password.error.invalidEmail': 'Introduza um email válido.',
    'password.error.longEmail': 'O email é demasiado longo.',
    'password.error.rateLimit': 'Aguarde alguns segundos antes de tentar novamente.',
    'password.error.locked': 'Muitas tentativas. Tente novamente dentro de {minutes} minuto(s).',
    'password.error.notFound': 'Email não encontrado. Verifique o endereço introduzido.',
    'password.error.tooMany': 'Foram efetuadas demasiadas tentativas. Tente novamente mais tarde.',
    'password.error.resetGeneric': 'Não foi possível enviar o email de recuperação.',
    'password.resetSent': 'Email de recuperação enviado. Consulte a caixa de entrada.',
    'onboarding.accountType.title': 'Escolha o tipo de conta',
    'onboarding.accountType.description': 'Selecione a opção que melhor corresponde à forma como pretende utilizar a plataforma.',
    'onboarding.accountType.created': 'Conta criada com sucesso. Complete agora a configuração do perfil.',
    'onboarding.accountType.personal': 'Conta pessoal',
    'onboarding.accountType.personalDescription': 'Para utilização individual, pedidos de cotação, lojas e serviços disponíveis na plataforma.',
    'onboarding.accountType.business': 'Conta empresarial',
    'onboarding.accountType.businessDescription': 'Para empresas que pretendem gerir produtos, cotações e relações comerciais.',
    'onboarding.accountType.select': 'Selecionar',
    'onboarding.accountType.selected': 'Selecionado',
    'onboarding.accountType.continue': 'Continuar',
    'onboarding.accountType.processing': 'A processar...',
    'onboarding.accountType.required': 'Selecione um tipo de conta para continuar.',
    'register.title': 'Criar nova conta',
    'register.create': 'Criar conta',
    'register.creating': 'A criar conta...',
    'register.haveAccount': 'Já tem uma conta?',
    'register.signIn': 'Entrar agora',
    'register.locked': 'Muitas tentativas. Tente novamente dentro de {minutes} minuto(s).',
    'register.password.minLength': 'Mínimo de 8 caracteres',
    'register.password.uppercase': 'Pelo menos uma letra maiúscula',
    'register.password.lowercase': 'Pelo menos uma letra minúscula',
    'register.password.number': 'Pelo menos um número',
    'register.password.special': 'Pelo menos um carácter especial (@$!%*?&)',
    'onboarding.loadingExisting': 'A verificar dados existentes...',
    'onboarding.companyTitle': 'Configuração da empresa',
    'onboarding.personalTitle': 'Configuração do perfil',
    'onboarding.backLogin': 'Voltar ao login',
    'onboarding.back': 'Voltar',
    'onboarding.next': 'Próximo',
    'onboarding.finish': 'Concluir configuração',
    'onboarding.processing': 'A processar...',
    'onboarding.step': 'Passo {current} de {total}',
    'onboarding.basicInfo': 'Informações básicas',
    'onboarding.addressContact': 'Endereço e contacto',
  },
  en: {
    'app.loadingSession': 'Checking authentication...',
    'app.sessionError': 'We could not load your session. Please try again.',
    'layout.skipToContent': 'Skip to main content',
    'layout.loadingProfile': 'Loading profile...',
    'preferences.lightMode': 'Enable light mode',
    'preferences.darkMode': 'Enable dark mode',
    'preferences.changeToEnglish': 'Change language to English',
    'preferences.changeToPortuguese': 'Change language to Portuguese',
    'preferences.theme': 'Theme',
    'preferences.light': 'Light',
    'preferences.dark': 'Dark',
    'dashboard.loading': 'Loading dashboard...',
    'dashboard.welcome': 'Welcome',
    'dashboard.user': 'User',
    'dashboard.verified': 'Verified',
    'dashboard.sectorMissing': 'Sector not defined',
    'dashboard.emailMissing': 'Email not defined',
    'dashboard.locationMissing': 'Location not defined',
    'dashboard.memberSince': 'Member since',
    'dashboard.newPost': 'New post',
    'dashboard.allProvinces': 'All provinces',
    'dashboard.logout': 'Sign out',
    'dashboard.modules': 'Modules',
    'dashboard.activeModulesCount': '{count} active module(s)',
    'modules.loading': 'Loading modules...',
    'modules.market.name': 'Products and services',
    'modules.market.description': 'List your products and services',
    'modules.alert.name': 'Alerts',
    'modules.alert.description': 'Receive requests and quotation enquiries',
    'modules.open': 'Open {name}',
    'modules.subscribe': 'Subscribe to {name}',
    'modules.active': 'Active',
    'modules.locked': 'Locked',
    'modules.available': 'Available',
    'modules.unavailable': 'Unavailable — subscribe to access',
    'nav.home': 'Home page',
    'nav.primary': 'Primary navigation',
    'nav.suppliers': 'Suppliers',
    'nav.stores': 'Stores',
    'nav.feed': 'Feed',
    'feed.title': 'Feed',
    'feed.description': 'Discover projects, work and stories from companies on Connection Mozambique.',
    'feed.companyFilter': 'Filter posts by company',
    'feed.allCompanies': 'All companies',
    'feed.loading': 'Loading posts...',
    'feed.loadError': 'We could not load the posts. Please try again.',
    'feed.retry': 'Try again',
    'feed.empty': 'No posts found',
    'feed.emptyHelp': 'New company posts will appear here.',
    'feed.emptyCompany': 'This company does not have any available posts yet.',
    'feed.noDescription': 'Post without a description.',
    'feed.dateUnknown': 'Date unavailable',
    'feed.openPost': 'Open post by',
    'gallery.label': 'Post gallery',
    'gallery.empty': 'No posts found',
    'gallery.emptyHelp': 'This company’s posts will appear here.',
    'gallery.companyUnknown': 'company',
    'gallery.openPost': 'Open post by {company}',
    'gallery.imageAlt': 'Work published by {company}',
    'profile.loading': 'Loading profile...',
    'profile.tabs.home': 'Home',
    'profile.tabs.about': 'About',
    'profile.tabs.posts': 'Posts',
    'profile.tabs.repository': 'Repository',
    'profile.companyInfo': 'Company information',
    'profile.generalInfo': 'General information',
    'profile.details': 'Details',
    'profile.aboutCompany': 'About the company',
    'profile.mission': 'Mission, vision and values',
    'profile.address': 'Address',
    'profile.contact': 'Contact',
    'profile.email': 'Email',
    'profile.sector': 'Sector',
    'profile.entityType': 'Entity type',
    'profile.location': 'Location',
    'profile.provinceDistrict': 'Province/District',
    'profile.productionCapacity': 'Production capacity',
    'profile.notProvided': 'Not provided',
    'profile.noContent': 'No content available.',
    'profile.noInformation': 'No information has been provided.',
    'profile.visits': 'Visits',
    'profile.connections': 'Connections',
    'profile.quotes': 'Quotes',
    'profile.edit': 'Edit profile',
    'profile.readMore': 'Read more',
    'profile.readLess': 'Show less',
    'profile.copyLink': 'Copy link',
    'profile.copySuccess': 'Link copied.',
    'profile.copyError': 'The link could not be copied.',
    'profile.imageTooLarge': 'The image is too large (maximum 25 MB).',
    'profile.imageTypeError': 'Unsupported format. Use JPEG, PNG or WEBP.',
    'profile.imageProcessError': 'The image could not be processed.',
    'profile.cropError': 'The image could not be cropped.',
    'profile.photoSuccess': 'Photo updated.',
    'profile.photoError': 'The photo could not be updated.',
    'profile.blocked': 'Company blocked',
    'profile.block': 'Block company',
    'profile.unblock': 'Unblock company',
    'profile.report': 'Report company',
    'profile.loginForOptions': 'Sign in to access these options.',
    'profile.noCover': 'No cover photo',
    'profile.companyNotFound': 'Company not found.',
    'profile.loadError': 'The profile could not be loaded.',
    'profile.authConnect': 'Sign in to connect with companies.',
    'profile.connectSuccess': 'Connection request sent.',
    'profile.connectError': 'The connection request could not be sent.',
    'profile.cancelConnectionSuccess': 'Connection request cancelled.',
    'profile.cancelConnectionError': 'The connection request could not be cancelled.',
    'profile.disconnectSuccess': 'Connection ended.',
    'profile.disconnectError': 'The connection could not be ended.',
    'profile.authReport': 'Sign in to report a company.',
    'profile.reasonRequired': 'Select a reason.',
    'profile.reportSuccess': 'Report sent. Thank you for your feedback.',
    'profile.reportError': 'The report could not be sent.',
    'profile.authBlock': 'Sign in to block a company.',
    'profile.blockSuccess': 'Company blocked.',
    'profile.blockError': 'The company could not be blocked.',
    'profile.unblockSuccess': 'Company unblocked.',
    'profile.unblockError': 'The company could not be unblocked.',
    'profile.processingImage': 'Processing image...',
    'profile.cropTitle': 'Crop image',
    'profile.cropAlt': 'Image to crop',
    'profile.cancel': 'Cancel',
    'profile.applyCrop': 'Apply crop',
    'profile.close': 'Close',
    'profile.share': 'Share profile',
    'profile.shareFacebook': 'Share on Facebook',
    'profile.shareTwitter': 'Share on X',
    'profile.shareWhatsApp': 'Share on WhatsApp',
    'profile.shareEmail': 'Share by email',
    'profile.connect': 'Connect',
    'profile.cancelRequest': 'Cancel request',
    'profile.disconnect': 'Disconnect',
    'profile.loginToConnect': 'Sign in to connect',
    'profile.openStore': 'Open store',
    'profile.call': 'Call',
    'profile.sendEmail': 'Send email',
    'profile.reportTitle': 'Report company',
    'profile.sendReport': 'Send report',
    'profile.blockTitle': 'Block company',
    'profile.blockWarning': 'When you block this company:',
    'profile.blockEffectConnections': 'You will not be able to send connection requests',
    'profile.blockEffectQuotes': 'You will not receive quote requests',
    'profile.customReason': 'Describe the reason in detail',
    'profile.confirmBlock': 'Confirm block',
    'profile.disconnectTitle': 'Confirm disconnection',
    'profile.disconnectQuestion': 'Are you sure you want to disconnect from {company}?',
    'profile.disconnectEffect': 'This company will be removed from your customer list.',
    'profile.reportReasonPrompt': 'Select the reason for the report:',
    'profile.blockReasonPrompt': 'Select the reason for blocking:',
    'profile.reason.inappropriate': 'Inappropriate content',
    'profile.reason.spam': 'Spam or unwanted messages',
    'profile.reason.personal': 'Personal issues',
    'profile.reason.unnecessary': 'Irrelevant company',
    'profile.reason.offensive': 'Offensive content',
    'profile.reason.falseInformation': 'False information',
    'profile.reason.misconduct': 'Inappropriate conduct',
    'profile.reason.terms': 'Terms violation',
    'profile.reason.other': 'Other reason',
    'profileEdit.title': 'Edit profile',
    'profileEdit.description': 'Manage your company information',
    'profileEdit.loading': 'Loading profile editor...',
    'profileEdit.tabs.profile': 'Profile',
    'profileEdit.tabs.password': 'Password',
    'profileEdit.tabs.bank': 'Bank details',
    'profileEdit.tabs.social': 'Social media',
    'profileEdit.tabs.showcase': 'Showcase',
    'profileEdit.companyName': 'Company name',
    'profileEdit.name': 'Name',
    'profileEdit.acronym': 'Acronym',
    'profileEdit.bio': 'Bio (maximum {count} characters)',
    'profileEdit.bioPlaceholder': 'Write a short description of the company...',
    'profileEdit.province': 'Province',
    'profileEdit.productionCapacity': 'Main activity production capacity',
    'profileEdit.save': 'Save changes',
    'profileEdit.saveSocial': 'Save social media',
    'profileEdit.saveSuccess': 'Details updated.',
    'profileEdit.saveError': 'The details could not be updated.',
    'profileEdit.userMissing': 'User not found.',
    'profileEdit.youtubeHelp': 'Paste the full link of the YouTube video you want to feature.',
    'profileEdit.videoPreview': 'Video preview',
    'personalProfile.defaultName': 'User',
    'personalProfile.changePhoto': 'Change profile photo',
    'personalProfile.invalidPhoto': 'Select an image no larger than 5 MB.',
    'personalProfile.photoSuccess': 'Photo updated.',
    'personalProfile.photoError': 'The photo could not be updated.',
    'personalProfile.province': 'Province',
    'personalProfile.saveProvince': 'Save province',
    'personalProfile.locationSuccess': 'Location updated.',
    'personalProfile.locationError': 'The location could not be updated.',
    'personalProfile.logout': 'Sign out',
    'personalProfile.logoutError': 'You could not be signed out.',
    'postDetail.loadError': 'We could not load this post.',
    'postDetail.notFound': 'Post not found',
    'postDetail.back': 'Back',
    'postDetail.authRequired': 'Sign in to perform this action.',
    'postDetail.permissionDenied': 'You do not have permission to perform this action.',
    'postDetail.noDescription': 'Post without a description.',
    'postDetail.companyUnknown': 'Unknown company',
    'postDetail.imageAlt': 'Image published by {company}',
    'postDetail.imageUnavailable': 'Image unavailable',
    'postDetail.like': 'Like',
    'postDetail.unlike': 'Unlike',
    'postDetail.edit': 'Edit',
    'postDetail.delete': 'Delete',
    'postDetail.deleteTitle': 'Delete post?',
    'postDetail.deleteHelp': 'This action is permanent. The post, likes and comments will no longer be available.',
    'postDetail.confirmDelete': 'Delete post',
    'postDetail.deleting': 'Deleting...',
    'postDetail.deleteError': 'The post could not be deleted. Please try again.',
    'postDetail.share': 'Share',
    'postDetail.report': 'Report',
    'postDetail.copyLink': 'Copy link',
    'postDetail.copySuccess': 'Link copied.',
    'postDetail.copyError': 'The link could not be copied.',
    'postDetail.likeSuccess': 'Post liked.',
    'postDetail.unlikeSuccess': 'Like removed.',
    'postDetail.likeError': 'The like could not be updated.',
    'postDetail.comments': 'Comments ({count})',
    'postDetail.commentPlaceholder': 'Write a comment...',
    'postDetail.replyPlaceholder': 'Write your reply...',
    'postDetail.replying': 'Replying to a comment...',
    'postDetail.firstComment': 'Be the first to comment.',
    'postDetail.reply': 'Reply',
    'postDetail.cancel': 'Cancel',
    'postDetail.save': 'Save',
    'postDetail.reportTitle': 'Report post',
    'postDetail.reportHelp': 'Describe the reason for your report.',
    'postDetail.reportPlaceholder': 'Reason for reporting',
    'postDetail.sendReport': 'Send report',
    'postDetail.reportReasonRequired': 'Enter the reason for the report.',
    'postDetail.reportDuplicate': 'You have already reported this post.',
    'postDetail.reportSuccess': 'Report sent.',
    'postDetail.reportError': 'The report could not be sent.',
    'postDetail.commentSuccess': 'Comment added.',
    'postDetail.commentError': 'The comment could not be added.',
    'postDetail.replySuccess': 'Reply sent.',
    'postDetail.replyError': 'The reply could not be sent.',
    'postDetail.commentDeleteSuccess': 'Comment deleted.',
    'postDetail.commentDeleteError': 'The comment could not be deleted.',
    'postDetail.commentUpdateSuccess': 'Comment updated.',
    'postDetail.commentUpdateError': 'The comment could not be updated.',
    'postDetail.updateSuccess': 'Post updated.',
    'postEdit.title': 'Edit post',
    'postEdit.close': 'Close editor',
    'postEdit.description': 'Description',
    'postEdit.placeholder': 'Write your post...',
    'postEdit.descriptionRequired': 'The description cannot be empty.',
    'postEdit.saveError': 'We could not update the post. Please try again.',
    'postEdit.saving': 'Saving...',
    'postEdit.save': 'Save changes',
    'nav.signIn': 'Sign in',
    'nav.openMenu': 'Open menu',
    'nav.closeMenu': 'Close menu',
    'nav.companies': 'Companies',
    'nav.quotes': 'Quotations',
    'nav.sentQuotes': 'My requests',
    'market.sentQuotes.title': 'Requests sent to stores',
    'market.sentQuotes.description': 'Track quotation requests sent directly through the Marketplace.',
    'market.sentQuotes.loadError': 'We could not load your requests.',
    'market.sentQuotes.empty': 'You have not sent any store requests yet',
    'market.sentQuotes.emptyHelp': 'Explore the Marketplace and request a quotation directly from a store.',
    'market.sentQuotes.explore': 'Explore stores',
    'market.sentQuotes.callStore': 'Call store',
    'market.sentQuotes.emailStore': 'Send email',
    'market.sentQuotes.viewStore': 'View store',
    'market.sentQuotes.responseTitle': 'Store response',
    'market.sentQuotes.totalPrice': 'Total price',
    'market.sentQuotes.validUntil': 'Valid until',
    'market.sentQuotes.status.pending': 'Awaiting response',
    'market.sentQuotes.status.answered': 'Answered',
    'market.sentQuotes.status.expired': 'Expired',
    'market.sentQuotes.status.cancelled': 'Cancelled',
    'market.sentQuotes.status.accepted': 'Accepted',
    'market.sentQuotes.status.rejected': 'Rejected',
    'market.sentQuotes.status.revision_requested': 'Revision requested',
    'market.sentQuotes.accept': 'Accept offer',
    'market.sentQuotes.reject': 'Reject',
    'market.sentQuotes.requestRevision': 'Request revision',
    'market.sentQuotes.decision.accepted': 'Accept offer',
    'market.sentQuotes.decision.rejected': 'Reject offer',
    'market.sentQuotes.decision.revision_requested': 'Request a revision',
    'market.sentQuotes.decisionNote': 'Note to the store',
    'market.sentQuotes.revisionRequired': 'Explain what should be revised.',
    'market.sentQuotes.decisionError': 'We could not update the request.',
    'nav.notifications': 'Notifications',
    'nav.dashboard': 'Dashboard',
    'nav.profile': 'My profile',
    'nav.signOut': 'Sign out',
    'nav.signInOrRegister': 'Sign in / Register',
    'nav.verificationRequired': 'Verification required',
    'verification.title': 'Account under verification',
    'verification.description': 'Your details are being verified. You will receive a notification when the process is complete.',
    'verification.limited': 'Your account is not verified. Some features are limited.',
    'footer.about': 'Mozambique’s leading business platform. We connect buyers with verified suppliers, enabling business and supporting the national economy.',
    'footer.verifiedCompany': 'Verified company',
    'footer.quickLinks': 'Quick links',
    'footer.legalInformation': 'Legal information',
    'footer.contacts': 'Contacts',
    'footer.followUs': 'Follow us',
    'footer.home': 'Home',
    'footer.explore': 'Explore companies',
    'footer.services': 'Services',
    'footer.aboutUs': 'About us',
    'footer.contact': 'Contact',
    'footer.termsConditions': 'Terms and conditions',
    'footer.privacyPolicy': 'Privacy policy',
    'footer.cookiesPolicy': 'Cookie policy',
    'footer.hours': 'Mon - Sat: 8:00 - 17:00',
    'footer.copyright': '© {year} Connection Mozambique, LDA — Mozambique Business Platform. All rights reserved.',
    'footer.terms': 'Terms',
    'footer.privacy': 'Privacy',
    'payment.loading': 'Loading module...',
    'payment.notFoundTitle': 'Module not found',
    'payment.notFoundDescription': 'The module you are trying to open does not exist or has been removed.',
    'payment.backHome': 'Back to home page',
    'payment.validity': 'Validity',
    'payment.oneYear': '1 year',
    'payment.oneMonth': '1 month',
    'payment.price': 'Price',
    'payment.moduleValue': 'Module price',
    'payment.reference': 'Reference',
    'payment.phone': 'M-Pesa phone number',
    'payment.phoneInvalid': 'Invalid number. Use nine digits and a valid Mozambican mobile prefix.',
    'payment.phoneHelp': 'Enter the nine digits of the number, for example 841234567.',
    'payment.submit': 'Pay with M-Pesa',
    'payment.processing': 'Processing payment',
    'payment.success': 'Payment processed successfully. Your subscription has been activated.',
    'payment.continue': 'Continue to module',
    'payment.confirmingActivation': 'Payment approved. Confirming module activation...',
    'payment.waitingActivation': 'Waiting for activation',
    'payment.error.configuration': 'The payment service is not configured in this environment.',
    'payment.error.validation': 'Check the module and phone number before continuing.',
    'payment.error.authentication': 'Your session has ended. Sign in again to continue.',
    'payment.error.connection': 'The authentication service could not be reached. Try again shortly.',
    'payment.error.duplicate': 'This payment has already been processed. Wait for activation confirmation.',
    'payment.error.generic': 'The payment could not be processed.',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.currentPassword': 'Current password',
    'auth.newPassword': 'New password',
    'auth.confirmPassword': 'Confirm new password',
    'auth.welcomeBack': 'Welcome back',
    'auth.signInDescription': 'Sign in to your account to access the platform',
    'auth.accountLocked': 'Account locked',
    'auth.signingIn': 'Signing in...',
    'auth.signInWithEmail': 'Sign in with email',
    'auth.or': 'or',
    'auth.continueGoogle': 'Continue with Google',
    'auth.forgotPassword': 'Forgot your password?',
    'auth.noAccount': 'No account?',
    'auth.register': 'Register',
    'auth.showPassword': 'Show password',
    'auth.hidePassword': 'Hide password',
    'auth.security.secure': 'Secure connection',
    'auth.security.standard': 'Standard verification',
    'auth.security.additional': 'Additional verification required',
    'password.changeTitle': 'Change password',
    'password.updating': 'Updating...',
    'password.update': 'Update password',
    'password.error.mismatch': 'The passwords do not match.',
    'password.error.unauthenticated': 'User is not authenticated.',
    'password.error.generic': 'The password could not be updated. Check the information provided.',
    'password.error.weak': 'The new password must contain at least 8 characters.',
    'password.error.same': 'The new password must be different from the current password.',
    'password.error.current': 'The current password is incorrect.',
    'password.error.provider': 'This account does not use a password. Sign in with its linked provider.',
    'password.error.changeTooMany': 'Too many attempts. Wait and try again.',
    'password.requirements': 'Use at least 8 characters.',
    'password.success': 'Password updated successfully.',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'bank.title': 'Bank details',
    'bank.description': 'Manage the accounts used to receive payments. These details must belong to the named account holder.',
    'bank.addTab': 'Add account',
    'bank.editTab': 'Edit account',
    'bank.listTab': 'Saved accounts',
    'bank.bank': 'Bank',
    'bank.accountNumber': 'Account number',
    'bank.accountHolder': 'Account holder',
    'bank.nib': 'NIB',
    'bank.iban': 'IBAN',
    'bank.add': 'Save account',
    'bank.update': 'Update account',
    'bank.saving': 'Saving...',
    'bank.loading': 'Loading bank details',
    'bank.empty': 'No bank details have been saved yet.',
    'bank.required': 'Enter the account number and account holder.',
    'bank.userMissing': 'The user could not be identified.',
    'bank.loadError': 'The bank details could not be loaded.',
    'bank.createSuccess': 'Bank details saved.',
    'bank.updateSuccess': 'Bank details updated.',
    'bank.saveError': 'The bank details could not be saved.',
    'bank.deleteTitle': 'Delete bank details?',
    'bank.deleteDescription': 'This permanently removes this bank account from the profile.',
    'bank.deleteSuccess': 'Bank details deleted.',
    'bank.deleteError': 'The bank details could not be deleted.',
    'showcase.title': 'Document showcase',
    'showcase.description': 'View and download public documents shared by the company.',
    'showcase.loading': 'Loading documents',
    'showcase.empty': 'No documents have been published yet.',
    'showcase.document': 'Document',
    'showcase.noDescription': 'No description.',
    'showcase.download': 'Download',
    'showcase.loadError': 'The documents could not be loaded.',
    'showcase.deleteTitle': 'Delete document?',
    'showcase.deleteDescription': 'The document and its file will be permanently removed.',
    'showcase.deleting': 'Deleting...',
    'showcase.deleteSuccess': 'Document deleted.',
    'showcase.deleteError': 'The document could not be deleted.',
    'fileUpload.title': 'Publish documents',
    'fileUpload.policyTitle': 'Document publishing policy',
    'fileUpload.allowedTitle': 'Allowed documents',
    'fileUpload.disallowedTitle': 'Disallowed documents',
    'fileUpload.select': 'Select files',
    'fileUpload.remove': 'Remove file',
    'fileUpload.description': 'Add a description...',
    'fileUpload.clear': 'Clear selection',
    'fileUpload.start': 'Start publishing',
    'fileUpload.uploading': 'Uploading ({current}/{count})',
    'fileUpload.selectionSummary': '{selected} of {count} files selected · maximum {size} MB per file',
    'fileUpload.maxFiles': 'You may upload no more than {count} files at a time.',
    'fileUpload.invalidType': 'Unsupported format: {name}',
    'fileUpload.tooLarge': '{name} exceeds the {size} MB limit.',
    'fileUpload.userMissing': 'The user could not be identified.',
    'fileUpload.noneSelected': 'Select at least one file.',
    'fileUpload.fileError': '{name} could not be uploaded.',
    'fileUpload.allSuccess': '{count} file(s) published successfully.',
    'fileUpload.partialSuccess': '{success} file(s) published; {failed} failed.',
    'fileUpload.noneSuccess': 'No files were published.',
    'fileUpload.cancel': 'Cancel uploads',
    'fileUpload.cancelled': 'The uploads were cancelled.',
    'fileUpload.allowedIntro': 'Only publish business documents intended for the public, such as:',
    'fileUpload.allowedHours': 'Business opening hours',
    'fileUpload.allowedManuals': 'Manuals, warranties, and return policies',
    'fileUpload.allowedRegulatory': 'Public tax or regulatory documents',
    'fileUpload.allowedOther': 'Other business documents suitable for public disclosure',
    'fileUpload.disallowedIntro': 'The following are not allowed:',
    'fileUpload.disallowedPromo': 'Advertisements, banners, or promotional gifts',
    'fileUpload.disallowedMarketing': 'Campaigns, contests, or other marketing materials',
    'fileUpload.disallowedUnrelated': 'Content unrelated to business documentation',
    'explore.loadError': 'The company directory could not be loaded. Please try again.',
    'common.close': 'Close',
    'explore.loading': 'Loading companies', 'explore.eyebrow': 'National company directory',
    'explore.title': 'Find companies, goods, and services', 'explore.description': 'Search for suppliers in Mozambique by name, activity, or location.',
    'explore.searchPlaceholder': 'Name, sector, or description…', 'explore.searchLabel': 'Search companies', 'explore.filters': 'Filters', 'explore.clear': 'Clear search and filters',
    'explore.results': '{count} company or companies found', 'explore.empty': 'No companies match your search. Adjust the filters and try again.',
    'explore.openCompany': 'Open {name} profile', 'explore.noSector': 'Sector not specified', 'explore.filterTitle': 'Filter companies',
    'explore.province': 'Province', 'explore.district': 'District', 'explore.sector': 'Sector', 'explore.subsector': 'Subsector', 'explore.entityType': 'Entity type',
    'explore.all': 'All', 'explore.clearFilters': 'Clear filters', 'explore.apply': 'View results',
    'dashboard.provinceTitle': 'Choose your location', 'dashboard.provinceDescription': 'Select a province for regional content or choose nationwide coverage.',
    'dashboard.national': 'Nationwide — all Mozambique', 'dashboard.confirmProvince': 'Save preference', 'dashboard.savingProvince': 'Saving...',
    'dashboard.provinceSaved': 'Location preference saved.', 'dashboard.provinceError': 'The location could not be saved.',
    'dashboard.provinceLoadError': 'The provinces could not be loaded.',
    'dashboard.eyebrow': 'Business across Mozambique', 'dashboard.title': 'Find companies, products, and services',
    'dashboard.description': 'Discover suppliers, compare solutions, and create new business opportunities on one platform.',
    'dashboard.searchPlaceholder': 'Search products or services…', 'dashboard.searchLabel': 'Search products or services', 'dashboard.search': 'Search',
    'dashboard.popular': 'Popular sectors:', 'dashboard.exploreCompanies': 'Explore companies', 'dashboard.exploreStores': 'Explore stores', 'dashboard.requestQuote': 'Request a quote',
    'emailVerification.title': 'Verify your email',
    'emailVerification.description': 'We sent a verification message to {email}. Open the link in that message to continue.',
    'emailVerification.support': 'If you need help, contact',
    'emailVerification.resend': 'Resend verification email',
    'emailVerification.resending': 'Resending...',
    'emailVerification.signOut': 'Sign out and return to login',
    'emailVerification.sent': 'Verification email resent. Check your inbox.',
    'emailVerification.error': 'The email could not be resent. Try again later.',
    'emailVerification.noUser': 'Your session has ended. Sign in again to continue.',
    'password.recoverTitle': 'Recover password',
    'password.recoverDescription': 'Enter your email to receive password recovery instructions.',
    'password.sendLink': 'Send recovery link',
    'password.sending': 'Sending...',
    'password.backToLogin': 'Back to login',
    'password.didNotReceive': 'Did not receive the email?',
    'password.resend': 'Resend',
    'password.checkSpam': 'Also check your spam or junk folder.',
    'password.error.requiredEmail': 'Enter your email.',
    'password.error.invalidEmail': 'Enter a valid email.',
    'password.error.longEmail': 'The email is too long.',
    'password.error.rateLimit': 'Wait a few seconds before trying again.',
    'password.error.locked': 'Too many attempts. Try again in {minutes} minute(s).',
    'password.error.notFound': 'Email not found. Check the address entered.',
    'password.error.tooMany': 'Too many attempts were made. Try again later.',
    'password.error.resetGeneric': 'The recovery email could not be sent.',
    'password.resetSent': 'Recovery email sent. Check your inbox.',
    'onboarding.accountType.title': 'Choose account type',
    'onboarding.accountType.description': 'Select the option that best matches how you intend to use the platform.',
    'onboarding.accountType.created': 'Account created successfully. Now complete your profile setup.',
    'onboarding.accountType.personal': 'Personal account',
    'onboarding.accountType.personalDescription': 'For individual use, quotation requests, stores, and services available on the platform.',
    'onboarding.accountType.business': 'Business account',
    'onboarding.accountType.businessDescription': 'For companies managing products, quotations, and business relationships.',
    'onboarding.accountType.select': 'Select',
    'onboarding.accountType.selected': 'Selected',
    'onboarding.accountType.continue': 'Continue',
    'onboarding.accountType.processing': 'Processing...',
    'onboarding.accountType.required': 'Select an account type to continue.',
    'register.title': 'Create a new account',
    'register.create': 'Create account',
    'register.creating': 'Creating account...',
    'register.haveAccount': 'Already have an account?',
    'register.signIn': 'Sign in now',
    'register.locked': 'Too many attempts. Try again in {minutes} minute(s).',
    'register.password.minLength': 'At least 8 characters',
    'register.password.uppercase': 'At least one uppercase letter',
    'register.password.lowercase': 'At least one lowercase letter',
    'register.password.number': 'At least one number',
    'register.password.special': 'At least one special character (@$!%*?&)',
    'onboarding.loadingExisting': 'Checking existing data...',
    'onboarding.companyTitle': 'Company setup',
    'onboarding.personalTitle': 'Profile setup',
    'onboarding.backLogin': 'Back to login',
    'onboarding.back': 'Back',
    'onboarding.next': 'Next',
    'onboarding.finish': 'Complete setup',
    'onboarding.processing': 'Processing...',
    'onboarding.step': 'Step {current} of {total}',
    'onboarding.basicInfo': 'Basic information',
    'onboarding.addressContact': 'Address and contact',
  },
};

const getInitialLanguage = () => {
  try {
    const storedLanguage = localStorage.getItem(STORAGE_KEY);
    if (storedLanguage === 'pt' || storedLanguage === 'en') return storedLanguage;
  } catch (error) {
    // Local storage may be unavailable in restricted browsing contexts.
  }

  return navigator.language?.toLowerCase().startsWith('en') ? 'en' : 'pt';
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(getInitialLanguage);

  const changeLanguage = useCallback((nextLanguage) => {
    if (nextLanguage === 'pt' || nextLanguage === 'en') {
      setLanguage(nextLanguage);
    }
  }, []);

  const t = useCallback((key, valuesOrFallback = key) => {
    const values = typeof valuesOrFallback === 'object' ? valuesOrFallback : {};
    const fallback = typeof valuesOrFallback === 'string' ? valuesOrFallback : key;
    const template = messages[language]?.[key] || messages.pt[key] || fallback;
    return Object.entries(values).reduce(
      (translated, [name, value]) => translated.replaceAll(`{${name}}`, String(value)),
      template,
    );
  }, [language]);

  useEffect(() => {
    document.documentElement.lang = language === 'pt' ? 'pt-MZ' : 'en';
    try {
      localStorage.setItem(STORAGE_KEY, language);
    } catch (error) {
      // Keep the in-memory preference when storage is unavailable.
    }
  }, [language]);

  const value = useMemo(() => ({
    language,
    changeLanguage,
    t,
  }), [language, changeLanguage, t]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
};
