import React, { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react';

const STORAGE_KEY = 'connection-language';
const LanguageContext = createContext();

const messages = {
  pt: {
    'app.loadingSession': 'Verificando autenticação...',
    'app.sessionError': 'Não foi possível carregar a sessão. Tente novamente.',
    'layout.skipToContent': 'Saltar para o conteúdo principal',
    'layout.loadingProfile': 'A carregar perfil...',
    'preferences.lightMode': 'Ativar modo claro',
    'preferences.darkMode': 'Ativar modo escuro',
    'preferences.changeToEnglish': 'Mudar idioma para inglês',
    'preferences.changeToPortuguese': 'Mudar idioma para português',
    'preferences.theme': 'Tema',
    'preferences.light': 'Claro',
    'preferences.dark': 'Escuro',
    'dashboard.loading': 'A carregar painel...',
    'dashboard.welcome': 'Bem-vindo(a)',
    'dashboard.user': 'Utilizador',
    'dashboard.verified': 'Verificado',
    'dashboard.sectorMissing': 'Setor não definido',
    'dashboard.emailMissing': 'Email não definido',
    'dashboard.locationMissing': 'Localização não definida',
    'dashboard.memberSince': 'Membro desde',
    'dashboard.newPost': 'Nova publicação',
    'dashboard.allProvinces': 'Todas as províncias',
    'dashboard.logout': 'Sair da conta',
    'dashboard.modules': 'Módulos',
    'dashboard.activeModulesCount': '{count} módulo(s) ativo(s)',
    'modules.loading': 'A carregar módulos...',
    'modules.market.name': 'Produtos e serviços',
    'modules.market.description': 'Cadastre os seus produtos e serviços',
    'modules.alert.name': 'Alertas',
    'modules.alert.description': 'Receba solicitações e pedidos de cotação',
    'modules.open': 'Abrir {name}',
    'modules.subscribe': 'Subscrever {name}',
    'modules.active': 'Ativo',
    'modules.locked': 'Bloqueado',
    'modules.available': 'Disponível',
    'modules.unavailable': 'Indisponível — subscreva para aceder',
    'nav.home': 'Página inicial',
    'nav.primary': 'Navegação principal',
    'nav.suppliers': 'Fornecedores',
    'nav.stores': 'Lojas',
    'nav.feed': 'Publicações',
    'feed.title': 'Publicações',
    'feed.description': 'Conheça projetos, trabalhos e histórias das empresas da Connection Mozambique.',
    'feed.companyFilter': 'Filtrar publicações por empresa',
    'feed.allCompanies': 'Todas as empresas',
    'feed.loading': 'A carregar publicações...',
    'feed.loadError': 'Não foi possível carregar as publicações. Tente novamente.',
    'feed.retry': 'Tentar novamente',
    'feed.empty': 'Nenhuma publicação encontrada',
    'feed.emptyHelp': 'As novas publicações das empresas aparecerão aqui.',
    'feed.emptyCompany': 'Esta empresa ainda não possui publicações disponíveis.',
    'feed.noDescription': 'Publicação sem descrição.',
    'feed.dateUnknown': 'Data não disponível',
    'feed.openPost': 'Abrir publicação de',
    'nav.signIn': 'Entrar',
    'nav.openMenu': 'Abrir menu',
    'nav.closeMenu': 'Fechar menu',
    'nav.companies': 'Empresas',
    'nav.quotes': 'Cotações',
    'nav.sentQuotes': 'Meus pedidos',
    'market.sentQuotes.title': 'Pedidos enviados às lojas',
    'market.sentQuotes.description': 'Acompanhe os pedidos de cotação que enviou diretamente pelo Mercado.',
    'market.sentQuotes.loadError': 'Não foi possível carregar os seus pedidos.',
    'market.sentQuotes.empty': 'Ainda não enviou pedidos a lojas',
    'market.sentQuotes.emptyHelp': 'Explore o Mercado e peça uma cotação diretamente a uma loja.',
    'market.sentQuotes.explore': 'Explorar lojas',
    'market.sentQuotes.callStore': 'Ligar para a loja',
    'market.sentQuotes.emailStore': 'Enviar email',
    'market.sentQuotes.viewStore': 'Ver loja',
    'market.sentQuotes.responseTitle': 'Resposta da loja',
    'market.sentQuotes.totalPrice': 'Preço total',
    'market.sentQuotes.validUntil': 'Válida até',
    'market.sentQuotes.status.pending': 'A aguardar resposta',
    'market.sentQuotes.status.answered': 'Respondido',
    'market.sentQuotes.status.expired': 'Expirado',
    'market.sentQuotes.status.cancelled': 'Cancelado',
    'market.sentQuotes.status.accepted': 'Aceite',
    'market.sentQuotes.status.rejected': 'Recusado',
    'market.sentQuotes.status.revision_requested': 'Revisão solicitada',
    'market.sentQuotes.accept': 'Aceitar proposta',
    'market.sentQuotes.reject': 'Recusar',
    'market.sentQuotes.requestRevision': 'Pedir revisão',
    'market.sentQuotes.decision.accepted': 'Aceitar proposta',
    'market.sentQuotes.decision.rejected': 'Recusar proposta',
    'market.sentQuotes.decision.revision_requested': 'Pedir revisão à loja',
    'market.sentQuotes.decisionNote': 'Nota para a loja',
    'market.sentQuotes.revisionRequired': 'Explique o que deve ser revisto.',
    'market.sentQuotes.decisionError': 'Não foi possível atualizar o pedido.',
    'nav.notifications': 'Notificações',
    'nav.dashboard': 'Painel',
    'nav.profile': 'Meu perfil',
    'nav.signOut': 'Sair',
    'nav.signInOrRegister': 'Entrar / Registar',
    'nav.verificationRequired': 'Verificação necessária',
    'verification.title': 'Conta em verificação',
    'verification.description': 'Os seus dados estão a ser verificados. Receberá uma notificação quando o processo terminar.',
    'verification.limited': 'A sua conta não está verificada. Algumas funcionalidades estão limitadas.',
    'footer.about': 'A maior plataforma empresarial de Moçambique. Ligamos compradores a fornecedores verificados, facilitando negócios e impulsionando a economia nacional.',
    'footer.verifiedCompany': 'Empresa verificada',
    'footer.quickLinks': 'Links rápidos',
    'footer.legalInformation': 'Informações legais',
    'footer.contacts': 'Contactos',
    'footer.followUs': 'Siga-nos',
    'footer.home': 'Início',
    'footer.explore': 'Explorar empresas',
    'footer.services': 'Serviços',
    'footer.aboutUs': 'Sobre nós',
    'footer.contact': 'Contacto',
    'footer.termsConditions': 'Termos e condições',
    'footer.privacyPolicy': 'Política de privacidade',
    'footer.cookiesPolicy': 'Política de cookies',
    'footer.hours': 'Seg - Sáb: 8:00 - 17:00',
    'footer.copyright': '© {year} Connection Mozambique, LDA — Plataforma Empresarial de Moçambique. Todos os direitos reservados.',
    'footer.terms': 'Termos',
    'footer.privacy': 'Privacidade',
    'payment.loading': 'A carregar módulo...',
    'payment.notFoundTitle': 'Módulo não encontrado',
    'payment.notFoundDescription': 'O módulo que está a tentar abrir não existe ou foi removido.',
    'payment.backHome': 'Voltar à página inicial',
    'payment.validity': 'Validade',
    'payment.oneYear': '1 ano',
    'payment.oneMonth': '1 mês',
    'payment.price': 'Preço',
    'payment.moduleValue': 'Valor do módulo',
    'payment.reference': 'Referência',
    'payment.phone': 'Telefone M-Pesa',
    'payment.phoneInvalid': 'Número inválido. Use nove dígitos e um prefixo móvel moçambicano válido.',
    'payment.phoneHelp': 'Introduza os nove dígitos do número, por exemplo 841234567.',
    'payment.submit': 'Pagar via M-Pesa',
    'payment.processing': 'A processar pagamento',
    'payment.success': 'Pagamento processado com sucesso. A sua subscrição foi ativada.',
    'payment.continue': 'Continuar para o módulo',
    'payment.confirmingActivation': 'Pagamento aprovado. A confirmar a ativação do módulo...',
    'payment.waitingActivation': 'A aguardar ativação',
    'payment.error.configuration': 'O serviço de pagamento não está configurado neste ambiente.',
    'payment.error.validation': 'Verifique o módulo e o número de telefone antes de continuar.',
    'payment.error.authentication': 'A sessão terminou. Entre novamente para continuar.',
    'payment.error.connection': 'Não foi possível contactar o serviço de autenticação. Tente novamente dentro de instantes.',
    'payment.error.duplicate': 'Este pagamento já foi processado. Aguarde a confirmação da ativação.',
    'payment.error.generic': 'Não foi possível processar o pagamento.',
    'auth.email': 'Email',
    'auth.password': 'Palavra-passe',
    'auth.currentPassword': 'Palavra-passe atual',
    'auth.newPassword': 'Nova palavra-passe',
    'auth.confirmPassword': 'Confirmar nova palavra-passe',
    'auth.welcomeBack': 'Bem-vindo de volta',
    'auth.signInDescription': 'Entre com a sua conta para aceder à plataforma',
    'auth.accountLocked': 'Conta bloqueada',
    'auth.signingIn': 'A entrar...',
    'auth.signInWithEmail': 'Entrar com email',
    'auth.or': 'ou',
    'auth.continueGoogle': 'Continuar com Google',
    'auth.forgotPassword': 'Esqueceu a palavra-passe?',
    'auth.noAccount': 'Não tem conta?',
    'auth.register': 'Registe-se',
    'auth.showPassword': 'Mostrar palavra-passe',
    'auth.hidePassword': 'Ocultar palavra-passe',
    'auth.security.secure': 'Ligação segura',
    'auth.security.standard': 'Verificação padrão',
    'auth.security.additional': 'Verificação adicional necessária',
    'password.changeTitle': 'Alterar palavra-passe',
    'password.updating': 'A atualizar...',
    'password.update': 'Atualizar palavra-passe',
    'password.error.mismatch': 'As palavras-passe não coincidem.',
    'password.error.unauthenticated': 'Utilizador não autenticado.',
    'password.error.generic': 'Não foi possível atualizar a palavra-passe. Verifique os dados introduzidos.',
    'password.success': 'Palavra-passe atualizada com sucesso.',
    'emailVerification.title': 'Verifique o seu email',
    'emailVerification.description': 'Enviámos uma mensagem de verificação para {email}. Abra a ligação recebida para continuar.',
    'emailVerification.support': 'Se precisar de ajuda, contacte',
    'emailVerification.resend': 'Reenviar email de verificação',
    'emailVerification.resending': 'A reenviar...',
    'emailVerification.signOut': 'Sair e voltar ao login',
    'emailVerification.sent': 'Email de verificação reenviado. Consulte a caixa de entrada.',
    'emailVerification.error': 'Não foi possível reenviar o email. Tente novamente mais tarde.',
    'emailVerification.noUser': 'A sessão terminou. Entre novamente para continuar.',
    'password.recoverTitle': 'Recuperar palavra-passe',
    'password.recoverDescription': 'Introduza o seu email para receber as instruções de recuperação.',
    'password.sendLink': 'Enviar ligação de recuperação',
    'password.sending': 'A enviar...',
    'password.backToLogin': 'Voltar ao login',
    'password.didNotReceive': 'Não recebeu o email?',
    'password.resend': 'Reenviar',
    'password.checkSpam': 'Verifique também a pasta de spam ou lixo eletrónico.',
    'password.error.requiredEmail': 'Introduza o seu email.',
    'password.error.invalidEmail': 'Introduza um email válido.',
    'password.error.longEmail': 'O email é demasiado longo.',
    'password.error.rateLimit': 'Aguarde alguns segundos antes de tentar novamente.',
    'password.error.locked': 'Muitas tentativas. Tente novamente dentro de {minutes} minuto(s).',
    'password.error.notFound': 'Email não encontrado. Verifique o endereço introduzido.',
    'password.error.tooMany': 'Foram efetuadas demasiadas tentativas. Tente novamente mais tarde.',
    'password.error.resetGeneric': 'Não foi possível enviar o email de recuperação.',
    'password.resetSent': 'Email de recuperação enviado. Consulte a caixa de entrada.',
    'onboarding.accountType.title': 'Escolha o tipo de conta',
    'onboarding.accountType.description': 'Selecione a opção que melhor corresponde à forma como pretende utilizar a plataforma.',
    'onboarding.accountType.created': 'Conta criada com sucesso. Complete agora a configuração do perfil.',
    'onboarding.accountType.personal': 'Conta pessoal',
    'onboarding.accountType.personalDescription': 'Para utilização individual, pedidos de cotação, lojas e serviços disponíveis na plataforma.',
    'onboarding.accountType.business': 'Conta empresarial',
    'onboarding.accountType.businessDescription': 'Para empresas que pretendem gerir produtos, cotações e relações comerciais.',
    'onboarding.accountType.select': 'Selecionar',
    'onboarding.accountType.selected': 'Selecionado',
    'onboarding.accountType.continue': 'Continuar',
    'onboarding.accountType.processing': 'A processar...',
    'onboarding.accountType.required': 'Selecione um tipo de conta para continuar.',
    'register.title': 'Criar nova conta',
    'register.create': 'Criar conta',
    'register.creating': 'A criar conta...',
    'register.haveAccount': 'Já tem uma conta?',
    'register.signIn': 'Entrar agora',
    'register.locked': 'Muitas tentativas. Tente novamente dentro de {minutes} minuto(s).',
    'register.password.minLength': 'Mínimo de 8 caracteres',
    'register.password.uppercase': 'Pelo menos uma letra maiúscula',
    'register.password.lowercase': 'Pelo menos uma letra minúscula',
    'register.password.number': 'Pelo menos um número',
    'register.password.special': 'Pelo menos um carácter especial (@$!%*?&)',
    'onboarding.loadingExisting': 'A verificar dados existentes...',
    'onboarding.companyTitle': 'Configuração da empresa',
    'onboarding.personalTitle': 'Configuração do perfil',
    'onboarding.backLogin': 'Voltar ao login',
    'onboarding.back': 'Voltar',
    'onboarding.next': 'Próximo',
    'onboarding.finish': 'Concluir configuração',
    'onboarding.processing': 'A processar...',
    'onboarding.step': 'Passo {current} de {total}',
    'onboarding.basicInfo': 'Informações básicas',
    'onboarding.addressContact': 'Endereço e contacto',
  },
  en: {
    'app.loadingSession': 'Checking authentication...',
    'app.sessionError': 'We could not load your session. Please try again.',
    'layout.skipToContent': 'Skip to main content',
    'layout.loadingProfile': 'Loading profile...',
    'preferences.lightMode': 'Enable light mode',
    'preferences.darkMode': 'Enable dark mode',
    'preferences.changeToEnglish': 'Change language to English',
    'preferences.changeToPortuguese': 'Change language to Portuguese',
    'preferences.theme': 'Theme',
    'preferences.light': 'Light',
    'preferences.dark': 'Dark',
    'dashboard.loading': 'Loading dashboard...',
    'dashboard.welcome': 'Welcome',
    'dashboard.user': 'User',
    'dashboard.verified': 'Verified',
    'dashboard.sectorMissing': 'Sector not defined',
    'dashboard.emailMissing': 'Email not defined',
    'dashboard.locationMissing': 'Location not defined',
    'dashboard.memberSince': 'Member since',
    'dashboard.newPost': 'New post',
    'dashboard.allProvinces': 'All provinces',
    'dashboard.logout': 'Sign out',
    'dashboard.modules': 'Modules',
    'dashboard.activeModulesCount': '{count} active module(s)',
    'modules.loading': 'Loading modules...',
    'modules.market.name': 'Products and services',
    'modules.market.description': 'List your products and services',
    'modules.alert.name': 'Alerts',
    'modules.alert.description': 'Receive requests and quotation enquiries',
    'modules.open': 'Open {name}',
    'modules.subscribe': 'Subscribe to {name}',
    'modules.active': 'Active',
    'modules.locked': 'Locked',
    'modules.available': 'Available',
    'modules.unavailable': 'Unavailable — subscribe to access',
    'nav.home': 'Home page',
    'nav.primary': 'Primary navigation',
    'nav.suppliers': 'Suppliers',
    'nav.stores': 'Stores',
    'nav.feed': 'Feed',
    'feed.title': 'Feed',
    'feed.description': 'Discover projects, work and stories from companies on Connection Mozambique.',
    'feed.companyFilter': 'Filter posts by company',
    'feed.allCompanies': 'All companies',
    'feed.loading': 'Loading posts...',
    'feed.loadError': 'We could not load the posts. Please try again.',
    'feed.retry': 'Try again',
    'feed.empty': 'No posts found',
    'feed.emptyHelp': 'New company posts will appear here.',
    'feed.emptyCompany': 'This company does not have any available posts yet.',
    'feed.noDescription': 'Post without a description.',
    'feed.dateUnknown': 'Date unavailable',
    'feed.openPost': 'Open post by',
    'nav.signIn': 'Sign in',
    'nav.openMenu': 'Open menu',
    'nav.closeMenu': 'Close menu',
    'nav.companies': 'Companies',
    'nav.quotes': 'Quotations',
    'nav.sentQuotes': 'My requests',
    'market.sentQuotes.title': 'Requests sent to stores',
    'market.sentQuotes.description': 'Track quotation requests sent directly through the Marketplace.',
    'market.sentQuotes.loadError': 'We could not load your requests.',
    'market.sentQuotes.empty': 'You have not sent any store requests yet',
    'market.sentQuotes.emptyHelp': 'Explore the Marketplace and request a quotation directly from a store.',
    'market.sentQuotes.explore': 'Explore stores',
    'market.sentQuotes.callStore': 'Call store',
    'market.sentQuotes.emailStore': 'Send email',
    'market.sentQuotes.viewStore': 'View store',
    'market.sentQuotes.responseTitle': 'Store response',
    'market.sentQuotes.totalPrice': 'Total price',
    'market.sentQuotes.validUntil': 'Valid until',
    'market.sentQuotes.status.pending': 'Awaiting response',
    'market.sentQuotes.status.answered': 'Answered',
    'market.sentQuotes.status.expired': 'Expired',
    'market.sentQuotes.status.cancelled': 'Cancelled',
    'market.sentQuotes.status.accepted': 'Accepted',
    'market.sentQuotes.status.rejected': 'Rejected',
    'market.sentQuotes.status.revision_requested': 'Revision requested',
    'market.sentQuotes.accept': 'Accept offer',
    'market.sentQuotes.reject': 'Reject',
    'market.sentQuotes.requestRevision': 'Request revision',
    'market.sentQuotes.decision.accepted': 'Accept offer',
    'market.sentQuotes.decision.rejected': 'Reject offer',
    'market.sentQuotes.decision.revision_requested': 'Request a revision',
    'market.sentQuotes.decisionNote': 'Note to the store',
    'market.sentQuotes.revisionRequired': 'Explain what should be revised.',
    'market.sentQuotes.decisionError': 'We could not update the request.',
    'nav.notifications': 'Notifications',
    'nav.dashboard': 'Dashboard',
    'nav.profile': 'My profile',
    'nav.signOut': 'Sign out',
    'nav.signInOrRegister': 'Sign in / Register',
    'nav.verificationRequired': 'Verification required',
    'verification.title': 'Account under verification',
    'verification.description': 'Your details are being verified. You will receive a notification when the process is complete.',
    'verification.limited': 'Your account is not verified. Some features are limited.',
    'footer.about': 'Mozambique’s leading business platform. We connect buyers with verified suppliers, enabling business and supporting the national economy.',
    'footer.verifiedCompany': 'Verified company',
    'footer.quickLinks': 'Quick links',
    'footer.legalInformation': 'Legal information',
    'footer.contacts': 'Contacts',
    'footer.followUs': 'Follow us',
    'footer.home': 'Home',
    'footer.explore': 'Explore companies',
    'footer.services': 'Services',
    'footer.aboutUs': 'About us',
    'footer.contact': 'Contact',
    'footer.termsConditions': 'Terms and conditions',
    'footer.privacyPolicy': 'Privacy policy',
    'footer.cookiesPolicy': 'Cookie policy',
    'footer.hours': 'Mon - Sat: 8:00 - 17:00',
    'footer.copyright': '© {year} Connection Mozambique, LDA — Mozambique Business Platform. All rights reserved.',
    'footer.terms': 'Terms',
    'footer.privacy': 'Privacy',
    'payment.loading': 'Loading module...',
    'payment.notFoundTitle': 'Module not found',
    'payment.notFoundDescription': 'The module you are trying to open does not exist or has been removed.',
    'payment.backHome': 'Back to home page',
    'payment.validity': 'Validity',
    'payment.oneYear': '1 year',
    'payment.oneMonth': '1 month',
    'payment.price': 'Price',
    'payment.moduleValue': 'Module price',
    'payment.reference': 'Reference',
    'payment.phone': 'M-Pesa phone number',
    'payment.phoneInvalid': 'Invalid number. Use nine digits and a valid Mozambican mobile prefix.',
    'payment.phoneHelp': 'Enter the nine digits of the number, for example 841234567.',
    'payment.submit': 'Pay with M-Pesa',
    'payment.processing': 'Processing payment',
    'payment.success': 'Payment processed successfully. Your subscription has been activated.',
    'payment.continue': 'Continue to module',
    'payment.confirmingActivation': 'Payment approved. Confirming module activation...',
    'payment.waitingActivation': 'Waiting for activation',
    'payment.error.configuration': 'The payment service is not configured in this environment.',
    'payment.error.validation': 'Check the module and phone number before continuing.',
    'payment.error.authentication': 'Your session has ended. Sign in again to continue.',
    'payment.error.connection': 'The authentication service could not be reached. Try again shortly.',
    'payment.error.duplicate': 'This payment has already been processed. Wait for activation confirmation.',
    'payment.error.generic': 'The payment could not be processed.',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.currentPassword': 'Current password',
    'auth.newPassword': 'New password',
    'auth.confirmPassword': 'Confirm new password',
    'auth.welcomeBack': 'Welcome back',
    'auth.signInDescription': 'Sign in to your account to access the platform',
    'auth.accountLocked': 'Account locked',
    'auth.signingIn': 'Signing in...',
    'auth.signInWithEmail': 'Sign in with email',
    'auth.or': 'or',
    'auth.continueGoogle': 'Continue with Google',
    'auth.forgotPassword': 'Forgot your password?',
    'auth.noAccount': 'No account?',
    'auth.register': 'Register',
    'auth.showPassword': 'Show password',
    'auth.hidePassword': 'Hide password',
    'auth.security.secure': 'Secure connection',
    'auth.security.standard': 'Standard verification',
    'auth.security.additional': 'Additional verification required',
    'password.changeTitle': 'Change password',
    'password.updating': 'Updating...',
    'password.update': 'Update password',
    'password.error.mismatch': 'The passwords do not match.',
    'password.error.unauthenticated': 'User is not authenticated.',
    'password.error.generic': 'The password could not be updated. Check the information provided.',
    'password.success': 'Password updated successfully.',
    'emailVerification.title': 'Verify your email',
    'emailVerification.description': 'We sent a verification message to {email}. Open the link in that message to continue.',
    'emailVerification.support': 'If you need help, contact',
    'emailVerification.resend': 'Resend verification email',
    'emailVerification.resending': 'Resending...',
    'emailVerification.signOut': 'Sign out and return to login',
    'emailVerification.sent': 'Verification email resent. Check your inbox.',
    'emailVerification.error': 'The email could not be resent. Try again later.',
    'emailVerification.noUser': 'Your session has ended. Sign in again to continue.',
    'password.recoverTitle': 'Recover password',
    'password.recoverDescription': 'Enter your email to receive password recovery instructions.',
    'password.sendLink': 'Send recovery link',
    'password.sending': 'Sending...',
    'password.backToLogin': 'Back to login',
    'password.didNotReceive': 'Did not receive the email?',
    'password.resend': 'Resend',
    'password.checkSpam': 'Also check your spam or junk folder.',
    'password.error.requiredEmail': 'Enter your email.',
    'password.error.invalidEmail': 'Enter a valid email.',
    'password.error.longEmail': 'The email is too long.',
    'password.error.rateLimit': 'Wait a few seconds before trying again.',
    'password.error.locked': 'Too many attempts. Try again in {minutes} minute(s).',
    'password.error.notFound': 'Email not found. Check the address entered.',
    'password.error.tooMany': 'Too many attempts were made. Try again later.',
    'password.error.resetGeneric': 'The recovery email could not be sent.',
    'password.resetSent': 'Recovery email sent. Check your inbox.',
    'onboarding.accountType.title': 'Choose account type',
    'onboarding.accountType.description': 'Select the option that best matches how you intend to use the platform.',
    'onboarding.accountType.created': 'Account created successfully. Now complete your profile setup.',
    'onboarding.accountType.personal': 'Personal account',
    'onboarding.accountType.personalDescription': 'For individual use, quotation requests, stores, and services available on the platform.',
    'onboarding.accountType.business': 'Business account',
    'onboarding.accountType.businessDescription': 'For companies managing products, quotations, and business relationships.',
    'onboarding.accountType.select': 'Select',
    'onboarding.accountType.selected': 'Selected',
    'onboarding.accountType.continue': 'Continue',
    'onboarding.accountType.processing': 'Processing...',
    'onboarding.accountType.required': 'Select an account type to continue.',
    'register.title': 'Create a new account',
    'register.create': 'Create account',
    'register.creating': 'Creating account...',
    'register.haveAccount': 'Already have an account?',
    'register.signIn': 'Sign in now',
    'register.locked': 'Too many attempts. Try again in {minutes} minute(s).',
    'register.password.minLength': 'At least 8 characters',
    'register.password.uppercase': 'At least one uppercase letter',
    'register.password.lowercase': 'At least one lowercase letter',
    'register.password.number': 'At least one number',
    'register.password.special': 'At least one special character (@$!%*?&)',
    'onboarding.loadingExisting': 'Checking existing data...',
    'onboarding.companyTitle': 'Company setup',
    'onboarding.personalTitle': 'Profile setup',
    'onboarding.backLogin': 'Back to login',
    'onboarding.back': 'Back',
    'onboarding.next': 'Next',
    'onboarding.finish': 'Complete setup',
    'onboarding.processing': 'Processing...',
    'onboarding.step': 'Step {current} of {total}',
    'onboarding.basicInfo': 'Basic information',
    'onboarding.addressContact': 'Address and contact',
  },
};

const getInitialLanguage = () => {
  try {
    const storedLanguage = localStorage.getItem(STORAGE_KEY);
    if (storedLanguage === 'pt' || storedLanguage === 'en') return storedLanguage;
  } catch (error) {
    // Local storage may be unavailable in restricted browsing contexts.
  }

  return navigator.language?.toLowerCase().startsWith('en') ? 'en' : 'pt';
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(getInitialLanguage);

  const changeLanguage = useCallback((nextLanguage) => {
    if (nextLanguage === 'pt' || nextLanguage === 'en') {
      setLanguage(nextLanguage);
    }
  }, []);

  const t = useCallback((key, valuesOrFallback = key) => {
    const values = typeof valuesOrFallback === 'object' ? valuesOrFallback : {};
    const fallback = typeof valuesOrFallback === 'string' ? valuesOrFallback : key;
    const template = messages[language]?.[key] || messages.pt[key] || fallback;
    return Object.entries(values).reduce(
      (translated, [name, value]) => translated.replaceAll(`{${name}}`, String(value)),
      template,
    );
  }, [language]);

  useEffect(() => {
    document.documentElement.lang = language === 'pt' ? 'pt-MZ' : 'en';
    try {
      localStorage.setItem(STORAGE_KEY, language);
    } catch (error) {
      // Keep the in-memory preference when storage is unavailable.
    }
  }, [language]);

  const value = useMemo(() => ({
    language,
    changeLanguage,
    t,
  }), [language, changeLanguage, t]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
};
